_wandb:
    value:
        cli_version: 0.30.0
        e:
            a570ahvra9jpjwcpqxuvoa9c3wrcqsm5:
                args:
                    - --source
                    - local
                    - --wandb-upload
                codePath: src/figures_generator/comparatifs_v2.py
                codePathLocal: src/figures_generator/comparatifs_v2.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "980650221568"
                        used: "556002181120"
                email: david.beauchemin.5@ulaval.ca
                executable: /home/david.beauchemin/Travail/articles/MeaningBERT/.venv/bin/python
                git:
                    commit: f2fe66ab17e1a86bafe6a50b1db3d6d13dfb102e
                    remote: git@github.com:GRAAL-Research/MeaningBERT.git
                host: UBU-FW13-012
                memory:
                    total: "32894971904"
                os: Linux-7.0.0-31-generic-x86_64-with-glibc2.39
                program: /home/david.beauchemin/Travail/articles/MeaningBERT/src/figures_generator/comparatifs_v2.py
                python: CPython 3.12.3
                root: /home/david.beauchemin/Travail/articles/MeaningBERT
                startedAt: "2026-09-25T11:51:14.044127Z"
                writerId: a570ahvra9jpjwcpqxuvoa9c3wrcqsm5
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 78
            "4": 3.12.3
            "5": 0.30.0
            "10":
                - 20
            "12": 0.30.0
            "13": linux-x86_64
